### ISSUE TITLE
Error missing directory

### ISSUE THREAD

**Issue by spuder** [sciapp/gitlab-registry-cleanup#12]
When I try and run `gitlab-registry-cleanup` from my workstation, I get the following error that a directory is missing, even though the directory is present. 
```
No such file or directory: '/var/opt/gitlab/gitlab-rails/shared/registry/docker/registry/v2/repositories'
```

```
gitlab-registry-cleanup -g gitlab.example.com -r https://gitlab.example.com:4567 -u  foobar -n
Password:
Traceback (most recent call last):
  File "/usr/local/bin/gitlab-registry-cleanup", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/gitlab_registry_cleanup/cli.py", line 278, in main
    args.dry_run,
  File "/usr/local/lib/python3.7/site-packages/gitlab_registry_cleanup/cli.py", line 253, in cleanup_gitlab_registry
    notify_callback=console_output,
  File "/usr/local/lib/python3.7/site-packages/gitlab_registry_cleanup/cleanup.py", line 17, in soft_delete_untagged_imagehashes
    repositories = sorted(local_registry.repository_paths)
  File "/usr/local/lib/python3.7/site-packages/gitlab_registry_cleanup/registry.py", line 109, in repository_paths
    self._repository_paths = self._find_all_repository_paths()
  File "/usr/local/lib/python3.7/site-packages/gitlab_registry_cleanup/registry.py", line 30, in _find_all_repository_paths
    for root, directories, files in os.walk(self._docker_repositories_root, onerror=on_error)
  File "/usr/local/lib/python3.7/site-packages/gitlab_registry_cleanup/registry.py", line 29, in <listcomp>
    os.path.relpath(root, self._docker_repositories_root)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 352, in walk
    onerror(error)
  File "/usr/local/lib/python3.7/site-packages/gitlab_registry_cleanup/registry.py", line 26, in on_error
    raise error
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 349, in walk
    scandir_it = scandir(top)
FileNotFoundError: [Errno 2] No such file or directory: '/var/opt/gitlab/gitlab-rails/shared/registry/docker/registry/v2/repositories'
```

**Comment by IngoMeyer441** [comment]
Hey, thanks for using my tool. 😃 `gitlab-registry-cleanup` can only be run on the GitLab server itself. Or do you have a local GitLab installation on your workstation?
Btw.: GitLab integrated a cleanup mechanism in v11.10, so this tool is not needed any more (see the deprecation notice in the [README](https://github.com/sciapp/gitlab-registry-cleanup/blob/develop/README.md)).

**Comment by spuder** [comment]
It wasn't clear to me it had to be on the gitlab server. I've also since discovered the built in clean up. Thanks
