### ISSUE TITLE
Does it work with custom registry directory?

### ISSUE THREAD

**Issue by rtyshyk** [sciapp/gitlab-registry-cleanup#9]
I have an issue with it, seems like it does not work with custom registry directory. I use separate volume for docker registry

The storage was changed via gitlab.rb

`gitlab_rails['registry_path'] = "/mnt/gitlab-docker-registry"`

```
root@c53d085600c9:~# gitlab-registry-cleanup -g https://git.example.com -r https://registry.example.com -c pwd -u rtyshyk -n
Traceback (most recent call last):
  File "/usr/local/bin/gitlab-registry-cleanup", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/gitlab_registry_cleanup/cli.py", line 204, in main
    cleanup_gitlab_registry(args.gitlab_server, args.registry_server, args.username, args.password, args.dry_run)
  File "/usr/local/lib/python3.6/dist-packages/gitlab_registry_cleanup/cli.py", line 195, in cleanup_gitlab_registry
    gitlab_base_url, registry_base_url, username, password, dry_run=dry_run, notify_callback=console_output
  File "/usr/local/lib/python3.6/dist-packages/gitlab_registry_cleanup/cleanup.py", line 17, in soft_delete_untagged_imagehashes
    repositories = sorted(local_registry.repository_paths)
  File "/usr/local/lib/python3.6/dist-packages/gitlab_registry_cleanup/registry.py", line 101, in repository_paths
    self._repository_paths = self._find_all_repository_paths()
  File "/usr/local/lib/python3.6/dist-packages/gitlab_registry_cleanup/registry.py", line 30, in _find_all_repository_paths
    for root, directories, files in os.walk(self._docker_repositories_root, onerror=on_error)
  File "/usr/local/lib/python3.6/dist-packages/gitlab_registry_cleanup/registry.py", line 29, in <listcomp>
    os.path.relpath(root, self._docker_repositories_root)
  File "/usr/lib/python3.6/os.py", line 351, in walk
    onerror(error)
  File "/usr/local/lib/python3.6/dist-packages/gitlab_registry_cleanup/registry.py", line 26, in on_error
    raise error
  File "/usr/lib/python3.6/os.py", line 348, in walk
    scandir_it = scandir(top)
FileNotFoundError: [Errno 2] No such file or directory: '/var/opt/gitlab/gitlab-rails/shared/registry/docker/registry/v2/repositories'
```

**Comment by IngoMeyer441** [comment]
Yes, you are right, currently the GitLab registry location cannot be configured. I can add an option for this.

**Comment by rtyshyk** [comment]
@IngoHeimbach Thanks!

**Comment by IngoMeyer441** [comment]
Sorry for waiting so long, I was quite busy... but finally [v0.1.4](https://pypi.org/project/gitlab-registry-cleanup/0.1.4/) is out and adds a `-p` / `--registry-path` switch that should suit your needs.

**Comment by IngoMeyer441** [comment]
As a bonus I plan to add a simple GitLab config parser. So in future, it won't be necessary to use command line switches for the server and registry url and the registry storage location at all.
